### ISSUE TITLE
Tomorrow, yesterday

### ISSUE THREAD

**Issue by millette** [Knutakir/week-number#4]
Instead of passing a date object, it would be handy (for the cli mostly - maybe I should sumbit there directly?) to handle a few strings like "Yesterday" or "tomorrow". I can send a PR.

**Comment by knutkirkhorn** [comment]
Thanks for the suggestion, I like it!

Maybe it could be useful to this package as well and implement own functions for these? For example like: `weekNumber.yesterday()` and `weekNumber.tomorrow()`? And then in the CLI it would check if the input is `yesterday` and just call it's respective function for that.

Feel free to open a PR for it, if you want 😊

**Comment by millette** [comment]
Great, I'll get to it this week, cheers!

**Comment by millette** [comment]
If/when that is approved, I'll send a PR for the cli.

**Comment by knutkirkhorn** [comment]
@millette I just merged your PR and pushed a new version (2.1.0)

**Comment by millette** [comment]
Great, thanks! Sorry I didn't update the readme, completely forgot about that :-)

**Comment by knutkirkhorn** [comment]
No worries, does it myself all the time 😅
